language: r

r:
  - release
  - devel

r_check_args: --as-cran --run-donttest

warnings_are_errors: true

cache: packages

r_packages:
  - covr

#r_github_packages:
#  - mangothecat/visualTest

after_success:
  - Rscript -e 'library("covr"); codecov(type="all")'
