language: r
r:
 - release
 - devel
sudo: false
warnings_are_errors: true
cache: packages

#r_build_args: --no-manual --no-resave-data
#r_check_args: --as-cran --run-donttest --no-build-vignettes --no-manual
#
#before_install:
# - tlmgr install fancyvrb units nag capt-of zlmtt environ

addons:
   apt:
     packages:
       - r-cran-devtools
       - r-cran-rcpp
       - r-cran-rcpparmadillo
       - devtools

r_binary_packages:
 - numDeriv
 - lava
 - testthat
 - futile.logger
 - mets
 - covr

#r_github_packages:
# - jimhester/covr
# - mangothecat/visualTest

install:
- R -e 'devtools::install_deps(dep = T)'

script:
- make rcheck

after_success:
  - Rscript -e 'library("covr"); codecov(type="test")'
